name: spa-admin-$(Build.SourceBranchName)-$(rev:rso)

trigger:
  - test


pr:
  - test


pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: isDevelop
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
  - name: isRelease
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/release')]
  - name: isHotfix
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')]
  - name: isFeature
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')]

stages:
  - stage: build
    displayName: 'Build'
    jobs:
      - job: build
        steps:
          - task: NodeTool@0
            displayName: 'Use Node 14.15.0'
            inputs:
              versionSpec: 14.15.0

          - bash: 'npm install npm@6.13.4 -g'
            displayName: 'Update npm'
            enabled: true

          - task: Npm@1
            displayName: 'npm install'
            inputs:
              verbose: false

          - task: Npm@1
            displayName: 'npm build dev'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run build --server=dev'

          - task: ArchiveFiles@2
            displayName: 'Archive files dev'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/spa-admin.zip'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: spa-admin-dev'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/spa-admin.zip'
              ArtifactName: 'spa-admin-dev'

          - bash: 'rm -rf $(System.DefaultWorkingDirectory)/build'
            displayName: 'clean build dir'

          - task: Npm@1
            displayName: 'npm build qa'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run build --server=qa'

          - task: ArchiveFiles@2
            displayName: 'Archive files qa'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/spa-admin.zip'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: spa-admin-qa'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/spa-admin.zip'
              ArtifactName: 'spa-admin-qa'

          - bash: 'rm -rf $(System.DefaultWorkingDirectory)/build'
            displayName: 'clean build dir'

          - task: Npm@1
            displayName: 'npm build prod'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run build --server=prod'

          - task: ArchiveFiles@2
            displayName: 'Archive files prod'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/spa-admin.zip'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: spa-admin-prod'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/spa-admin.zip'
              ArtifactName: 'spa-admin-prod'

  - stage: deploydev
    displayName: 'Deploy to DEV'
    condition: and(or(eq(variables.isFeature, true), eq(variables.isDevelop, true)), ne(variables['Build.Reason'], 'PullRequest'))
    dependsOn: [build]
    variables:
      - group: creds-test
      - name: webAppName
        value: 'Test'
      - name: artifactName
        value: 'Test'
    jobs:
      - deployment: app
        displayName: 'Deploy to DEV'
        pool:
          vmImage: 'windows-2019'
        environment: TEST
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadPipelineArtifact@2
                displayName: 'Download $(artifactName)'
                inputs:
                  artifact: $(artifactName)
                  path: $(System.DefaultWorkingDirectory)/$(artifactName)

              - task: AzureRmWebAppDeployment@4
                displayName: 'Azure App Service Deploy spa-admin'
                inputs:
                  azureSubscription: 'Test'
                  appType: webApp
                  WebAppName: '$(webAppName)'
                  Package: '$(System.DefaultWorkingDirectory)/$(artifactName)/**/*.zip'
                  VirtualApplication: /Admin
                  enableCustomDeployment: true
                  RemoveAdditionalFilesFlag: true
                  ExcludeFilesFromAppDataFlag: false
                  RenameFilesFlag: false





